package LLD.TransactionFilteringSystem.enums;

public enum ValidationErrorType {
    INVALID_PAYMENT_METHOD_EXCEPTION,
    INVALID_DESCRIPTION_EXCEPTION,
    INVALID_AMOUNT_EXCEPTION,
    CUSTOMER_ID_INVALID_EXCEPTION,
    MERCHANT_ID_EXCEPTION,
    PAYMENT_STATUS_INVALID;

}
